name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: gcr.io/teak-facet-417311/your-image-name:latest
        context: .
    
    - name: Authenticate with Google Cloud
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: 'latest'
        service_account_key: ${{ secrets.GCP_SA_KEY }} # Set this secret in your repository's settings
        
    - name: Configure Docker with GCP credentials
      run: gcloud auth configure-docker
      
    - name: Deploy to GCP
      run: |
        docker pull gcr.io/teak-facet-417311/your-image-name:latest
        docker run -d --name your-container-name -p 80:80 gcr.io/teak-facet-417311/your-image-name:latest
